# Display Settings
DISPLAY_WIDTH = 256
DISPLAY_HEIGHT = 128
FRAMERATE = 10

# Fonts
FONT_SIZE_SMALL = 10
FONT_SIZE_MEDIUM = 16
FONT_SIZE_LARGE = 24

# API Settings
REFRESH_INTERVAL = 30 # seconds

# Platform 
PLATFORM_PC = "PC"
PLATFORM_PI = "PI"
